version: '3'
services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./strapi-backend:/srv/app
    ports:
      - '1337:1337'
  react-app:
    build:
      context: ./cdc-frontend-app
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./cdc-frontend-app/src:/app/src
    # environment: 
    #   - REACT_APP_NAME=cdc-frontend
    # env_file: 
    #   - ./.env