version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-production/certs:/etc/nginx/certs
    acme-companion:
      image: nginxproxy/acme-companion
      container_name: nginx-proxy-acme
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./nginx-production/certs:/etc/nginx/certs:rw
        - ./nginx-production/acme:/etc/acme.sh
        - /var/run/docker.sock:/var/run/docker.sock:ro
  react-app:
    build:
      context: ./cdc-frontend-app
      dockerfile: Dockerfile.prod
    environment:
      - VIRTUAL_HOST=cdcunc.com
      # - VIRTUAL_HOST=localhost
  strapi:
    image: strapi/strapi
    volumes:
      - ./strapi-backend:/srv/app
    environment: 
      - NODE_ENV=production
      - VIRTUAL_HOST=api.cdcunc.com
