version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./nginx-production/certs:/etc/nginx/certs
  #     - ./nginx-production/vhost:/etc/nginx/vhost.d
  #     - ./nginx-production/html:/usr/share/nginx/html
  # letsencrypt-helper:
  #   image: nginxproxy/acme-companion
  #   volumes_from: 
  #     - nginx-proxy
  #   volumes: 
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./nginx-production/acme:/etc/acme.sh
  #   environment: 
  #     - DEFAULT_EMAIL=temp@temp.temp
  strapi:
    image: strapi/strapi
    volumes:
      - ./strapi-backend:/srv/app
    environment: 
      - NODE_ENV=production
      - VIRTUAL_HOST=api.cdcunc.com
      # - LETSENCRYPT_HOST=api.cdcunc.com
      # - LETSENCRYPT_EMAIL=temp@temp.temp
  react-app:
    build:
      context: ./cdc-frontend-app
      dockerfile: Dockerfile.prod
    environment: 
      - VIRTUAL_HOST=cdcunc.com
      # - LETSENCRYPT_HOST=cdcunc.com
      # - LETSENCRYPT_EMAIL=temp@temp.temp
      # - VIRTUAL_HOST=localhost