version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  strapi:
    image: strapi/strapi
    volumes:
      - ./strapi-backend:/srv/app
    environment: 
      - NODE_ENV=production
      - VIRTUAL_HOST=api.cdcunc.com
  react-app:
    build:
      context: ./cdc-frontend-app
      dockerfile: Dockerfile.prod
    environment: 
      - VIRTUAL_HOST=cdcunc.com
      # - VIRUTAL_HOST=localhost